name: Deploy to Heroku Stage (Server)

on:
  push:
    branches:
      - develop
    paths:
      - 'packages/server/**'
      - '.github/workflows/server-stage.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add server remote origin
        run: git remote add heroku-server https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_STAGE_SERVER_APP_NAME }}.git
      - name: Deploy server to Heroku
        run: git push heroku-server develop:master --force
