name: Deploy to Heroku Stage (Web)

on:
  push:
    branches:
      - develop
    paths:
      - 'packages/web/**'
      - 'packages/shared/**'
      - '.github/workflows/web-stage.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Add frontend remote origin
        run: git remote add heroku-frontend https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_STAGE_WEB_APP_NAME }}.git
      - name: Deploy frontend to Heroku
        run: git push heroku-frontend develop:master --force
