name: Deploy to Heroku (Web)

on:
  push:
    branches:
      - main
    paths:
      - 'packages/web/**'
      - 'packages/shared/**'
      - '.github/workflows/web.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add frontend remote origin
        run: git remote add heroku-frontend https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_WEB_APP_NAME }}.git
      - name: Deploy frontend to Heroku
        run: git push heroku-frontend main:master
